#!/usr/bin/env python
"""Build ref/macro_dates.csv: ISM Manufacturing and ISM Services release days (D-015).

ISM's published rule: Manufacturing on the first business day of the month, Services on
the third, both at 10:00 ET. ISM business days skip US federal holidays (as observed) and
Good Friday. ISM's past schedules are not archived on its site, so two points are
uncertain and both readings are kept:

* January: ISM now takes the first business day after New Year's Day off (in place by
  2021; not in 2017). Both candidate days are listed.
* Good Friday: treated as an ISM holiday in 2026; whether it always was is unknown, so in
  months where it changes the answer both candidate days are listed.

Listing an extra day costs one day of sample in an exploratory exclusion; missing a real
release day would leave a 10:00 burst in the data. Rows where the reading is ambiguous
have certain=False.

    python scripts/build_macro_dates.py            # writes ref/macro_dates.csv
"""

from __future__ import annotations

import sys
from itertools import product
from pathlib import Path

import pandas as pd
from pandas.tseries.holiday import GoodFriday, USFederalHolidayCalendar

ROOT = Path(__file__).resolve().parents[1]
RELEASES = {"ISM Manufacturing": 1, "ISM Services": 3}   # nth ISM business day


def ism_business_days(year: int, good_friday_off: bool, extra_january_off: bool) -> pd.DatetimeIndex:
    start, end = pd.Timestamp(year, 1, 1), pd.Timestamp(year, 12, 31)
    days = pd.bdate_range(start, end)
    hol = set(USFederalHolidayCalendar().holidays(start - pd.Timedelta(days=7), end))
    if good_friday_off:
        hol |= set(GoodFriday.dates(start, end))
    days = days[~days.isin(list(hol))]
    if extra_january_off:
        days = days.delete(0)                      # first business day after New Year's Day
    return days


def candidates(year: int, month: int, nth: int) -> list[pd.Timestamp]:
    out = set()
    for gf, jan in product([True, False], [True, False] if month == 1 else [False]):
        days = ism_business_days(year, gf, jan)
        out.add(days[days.month == month][nth - 1])
    return sorted(out)


def build(first_year: int, last_year: int) -> pd.DataFrame:
    rows = []
    for year in range(first_year, last_year + 1):
        for month in range(1, 13):
            for release, nth in RELEASES.items():
                cands = candidates(year, month, nth)
                certain = len(cands) == 1
                note = ""
                if not certain:
                    note = ("January: ISM's extra holiday after New Year's; both candidates kept"
                            if month == 1 else "Good Friday changes the count; both candidates kept")
                for d in cands:
                    rows.append({"date": d.date().isoformat(), "time_et": "10:00",
                                 "release": release, "certain": certain, "notes": note})
    return pd.DataFrame(rows)


HEADER = """\
# ISM Manufacturing and ISM Services release days, 10:00 ET (D-015).
# Generated by scripts/build_macro_dates.py from ISM's published rule (Manufacturing:
# first business day; Services: third; federal holidays and Good Friday skipped).
# certain=False rows: the rule is ambiguous that month and every candidate day is listed.
# Checked against ISM's published 2026 schedule and dated historical releases
# (tests/test_refdata.py). Do not edit by hand; rerun the script.
"""


def main() -> None:
    first, last = (int(a) for a in sys.argv[1:3]) if len(sys.argv) >= 3 else (2009, 2025)
    df = build(first, last)
    path = ROOT / "ref" / "macro_dates.csv"
    path.write_text(HEADER + df.to_csv(index=False))
    print(f"{len(df)} rows ({(~df['certain']).sum()} uncertain) -> {path}")


if __name__ == "__main__":
    main()
